version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/todoapp-0.0.1-SNAPSHOT.jar
    - Dockerfile
    - docker-compose.yml
